import { ProsperitasState } from "../core/schema-types";

export const CURRENT_SCHEMA_VERSION = "0.1";

/*
export const defaultState: ProsperitasState = {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    meta: {
        createdAt: "2025-12-22T00:00:00.000Z",
        updatedAt: "2025-12-22T00:00:00.000Z",
    },
    settings: {
        balanceCurrency: "EUR",
        visualCurrency: "EUR",
        locale: "en-PT",
        timezone: "GMT+0",
        numberFormat: {
            useGrouping: true,
            maxFractionDigits: 2,
        },
    },
    account: {
        name: "Miguel",
    },
    categories: {
        cat_0: {
            id: "cat_0",
            name: "Salary",
            type: "income",
            color: "#2ECC71",
        },
        cat_1: {
            id: "cat_1",
            name: "Food",
            type: "expense",
            color: "#E74C3C",
        },
    },
    balance: {
        "2025-12": {
            month: "2025-12",
            txs: [
                {
                    date: "2025-12-01",
                    type: "income",
                    categoryId: "cat_0",
                    amount: { value: 1500, currency: "EUR" },
                    description: "December salary",
                    createdAt: "2025-12-01T10:00:00.000Z",
                },
                {
                    date: "2025-12-01",
                    type: "expense",
                    categoryId: "cat_1",
                    amount: { value: 3.95, currency: "EUR" },
                    description: "coffee",
                    createdAt: "2025-12-20T10:00:00.000Z",
                },
            ],
        },
        "2026-01": {
            month: "2026-01",
            txs: [],
        },
    },
    assets: {
        a_0: {
            id: "a_0",
            ticker: "BTC",
            stooqTicker: null,
            tradingCurrency: "USD",
            name: "Bitcoin",
            assetType: "crypto",
            decimals: 8,
            amount: 0.0,
            avgCost: { value: 0, currency: "USD" },
            txIds: [],
            createdAt: "2025-12-22T00:00:00.000Z",
            updatedAt: "2025-12-22T00:00:00.000Z",
        },
        a_1: {
            id: "a_1",
            ticker: "VUAA",
            stooqTicker: null,
            tradingCurrency: "EUR",
            name: "Vanguard S&P 500 UCITS ETF",
            assetType: "etf",
            decimals: 6,
            amount: 0.0,
            avgCost: { value: 0, currency: "EUR" },
            txIds: [],
            createdAt: "2025-12-22T00:00:00.000Z",
            updatedAt: "2025-12-22T00:00:00.000Z",
        },
    },
    wallets: {
        wallet_0: {
            id: "wallet_0",
            name: "Coinbase",
            description: "Crypto exchange",
            cash: [
                { value: 0, currency: "EUR" },
                { value: 0, currency: "USD" },
            ],
            txIds: [],
        },
        wallet_1: {
            id: "wallet_1",
            name: "Binance",
            description: "Another crypto exchange",
            cash: [
                { value: 0, currency: "EUR" },
                { value: 0, currency: "USD" },
            ],
            txIds: [],
        },
    },
    walletPositions: {
        wallet_0: {
            a_0: { amount: 0.0, avgCost: { value: 0, currency: "USD" } },
            a_1: { amount: 0.0, avgCost: { value: 0, currency: "EUR" } },
        },
        wallet_1: {
            a_0: { amount: 0.0, avgCost: { value: 0, currency: "USD" } },
        },
    },
    walletTx: {
        tx_0: {
            id: "tx_0",
            walletId: "wallet_0",
            type: "deposit",
            date: "2025-12-10",
            amount: { value: 500, currency: "EUR" },
            createdAt: "2025-12-10T12:00:00.000Z",
        },
        tx_1: {
            id: "tx_1",
            walletId: "wallet_0",
            type: "forex",
            date: "2025-12-11",
            from: { value: 300, currency: "EUR" },
            to: { value: 330, currency: "USD" },
            fees: { value: 1.0, currency: "EUR" },
            createdAt: "2025-12-11T12:00:00.000Z",
        },
        tx_2: {
            id: "tx_2",
            walletId: "wallet_0",
            type: "buy",
            date: "2025-12-12",
            assetId: "a_0",
            quantity: 0.01,
            price: { value: 45000, currency: "USD" },
            fees: { value: 1.5, currency: "EUR" },
            createdAt: "2025-12-12T12:00:00.000Z",
        },
        tx_3: {
            id: "tx_3",
            walletId: "wallet_0",
            type: "sell",
            date: "2025-12-20",
            assetId: "a_0",
            quantity: 0.005,
            price: { value: 52000, currency: "USD" },
            fees: { value: 1.2, currency: "EUR" },
            createdAt: "2025-12-20T12:00:00.000Z",
        },
        tx_4: {
            id: "tx_4",
            walletId: "wallet_0",
            type: "withdraw",
            date: "2025-12-21",
            amount: { value: 50, currency: "EUR" },
            createdAt: "2025-12-21T12:00:00.000Z",
        },
    },
    pies: {
        pie_0: {
            id: "pie_0",
            name: "pie1",
            assetIds: ["a_0", "a_1"],
        },
        pie_1: {
            id: "pie_1",
            name: "pie2",
            assetIds: [],
        },
    },
};
*/

export const defaultState: ProsperitasState = {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    meta: {
        createdAt: "2025-12-27T00:00:00.000Z",
        updatedAt: "2025-12-27T00:00:00.000Z",
    },
    settings: {
        balanceCurrency: "EUR",
        visualCurrency: "EUR",
        locale: "en",
        timezone: "UTC",
        numberFormat: {
            useGrouping: true,
            maxFractionDigits: 2,
        },
    },
    account: {
        name: "",
    },
    categories: {},
    balance: {},
    assets: {},
    wallets: {},
    walletPositions: {},
    walletTx: {},
    pies: {},
    livePrices: {},
    notifications: [],
};

export const demoState: ProsperitasState = {
    schemaVersion: CURRENT_SCHEMA_VERSION,
    meta: {
        createdAt: "2025-03-05T09:00:00.000Z",
        updatedAt: "2025-04-10T14:30:00.000Z",
    },
    settings: {
        balanceCurrency: "EUR",
        visualCurrency: "EUR",
        locale: "en",
        timezone: "Europe/Lisbon",
        numberFormat: {
            useGrouping: true,
            maxFractionDigits: 2,
        },
    },
    account: {
        name: "Alex Pereira",
    },
    categories: {
        cat_salary: {
            id: "cat_salary",
            name: "Salary",
            type: "income",
            color: "#22C55E",
        },
        cat_bonus: {
            id: "cat_bonus",
            name: "Bonus",
            type: "income",
            color: "#10B981",
        },
        cat_rent: {
            id: "cat_rent",
            name: "Rent",
            type: "expense",
            color: "#F97316",
        },
        cat_groceries: {
            id: "cat_groceries",
            name: "Groceries",
            type: "expense",
            color: "#EF4444",
        },
        cat_utilities: {
            id: "cat_utilities",
            name: "Utilities",
            type: "expense",
            color: "#3B82F6",
        },
        cat_entertainment: {
            id: "cat_entertainment",
            name: "Entertainment",
            type: "expense",
            color: "#A855F7",
        },
        cat_travel: {
            id: "cat_travel",
            name: "Travel",
            type: "expense",
            color: "#06B6D4",
        },
        cat_health: {
            id: "cat_health",
            name: "Health",
            type: "expense",
            color: "#F43F5E",
        },
    },
    balance: {
        "2025-03": {
            month: "2025-03",
            txs: [
                {
                    date: "2025-03-01",
                    type: "income",
                    categoryId: "cat_salary",
                    amount: { value: 3400, currency: "EUR" },
                    description: "Monthly salary",
                    createdAt: "2025-03-01T08:30:00.000Z",
                },
                {
                    date: "2025-03-02",
                    type: "expense",
                    categoryId: "cat_rent",
                    amount: { value: 1200, currency: "EUR" },
                    description: "Apartment rent",
                    createdAt: "2025-03-02T09:15:00.000Z",
                },
                {
                    date: "2025-03-06",
                    type: "expense",
                    categoryId: "cat_groceries",
                    amount: { value: 138.6, currency: "EUR" },
                    description: "Weekly groceries",
                    createdAt: "2025-03-06T18:45:00.000Z",
                },
                {
                    date: "2025-03-11",
                    type: "expense",
                    categoryId: "cat_utilities",
                    amount: { value: 92.4, currency: "EUR" },
                    description: "Electricity & internet",
                    createdAt: "2025-03-11T10:05:00.000Z",
                },
                {
                    date: "2025-03-18",
                    type: "expense",
                    categoryId: "cat_entertainment",
                    amount: { value: 56.2, currency: "EUR" },
                    description: "Streaming & cinema",
                    createdAt: "2025-03-18T21:10:00.000Z",
                },
            ],
        },
        "2025-04": {
            month: "2025-04",
            txs: [
                {
                    date: "2025-04-01",
                    type: "income",
                    categoryId: "cat_salary",
                    amount: { value: 3400, currency: "EUR" },
                    description: "Monthly salary",
                    createdAt: "2025-04-01T08:35:00.000Z",
                },
                {
                    date: "2025-04-03",
                    type: "income",
                    categoryId: "cat_bonus",
                    amount: { value: 450, currency: "EUR" },
                    description: "Performance bonus",
                    createdAt: "2025-04-03T12:00:00.000Z",
                },
                {
                    date: "2025-04-05",
                    type: "expense",
                    categoryId: "cat_travel",
                    amount: { value: 220, currency: "EUR" },
                    description: "Weekend getaway",
                    createdAt: "2025-04-05T16:20:00.000Z",
                },
                {
                    date: "2025-04-09",
                    type: "expense",
                    categoryId: "cat_health",
                    amount: { value: 75, currency: "EUR" },
                    description: "Gym membership",
                    createdAt: "2025-04-09T07:45:00.000Z",
                },
            ],
        },
    },
    assets: {
        asset_vuaa: {
            id: "asset_vuaa",
            ticker: "VUAA",
            stooqTicker: null,
            tradingCurrency: "EUR",
            name: "Vanguard S&P 500 UCITS ETF",
            assetType: "etf",
            decimals: 6,
            amount: 18.5,
            avgCost: { value: 91.2, currency: "EUR" },
            txIds: ["tx_buy_vuaa", "tx_dividend_vuaa"],
            createdAt: "2025-03-10T10:00:00.000Z",
            updatedAt: "2025-04-08T10:00:00.000Z",
        },
        asset_btc: {
            id: "asset_btc",
            ticker: "BTC",
            stooqTicker: null,
            tradingCurrency: "USD",
            name: "Bitcoin",
            assetType: "crypto",
            decimals: 8,
            amount: 0.028,
            avgCost: { value: 41200, currency: "USD" },
            txIds: ["tx_buy_btc"],
            createdAt: "2025-03-15T14:20:00.000Z",
            updatedAt: "2025-04-06T09:05:00.000Z",
        },
    },
    wallets: {
        wallet_bank: {
            id: "wallet_bank",
            name: "Main Bank",
            description: "Daily spending account",
            cash: [
                { value: 2450, currency: "EUR" },
                { value: 320, currency: "USD" },
            ],
            txIds: [
                "tx_deposit_salary",
                "tx_withdraw_rent",
                "tx_forex_travel",
            ],
        },
        wallet_broker: {
            id: "wallet_broker",
            name: "Brokerage",
            description: "Long-term investments",
            cash: [
                { value: 860, currency: "EUR" },
                { value: 0, currency: "USD" },
            ],
            txIds: ["tx_buy_vuaa", "tx_buy_btc", "tx_dividend_vuaa"],
        },
    },
    walletPositions: {
        wallet_bank: {},
        wallet_broker: {
            asset_vuaa: {
                amount: 18.5,
                avgCost: { value: 91.2, currency: "EUR" },
            },
            asset_btc: {
                amount: 0.028,
                avgCost: { value: 41200, currency: "USD" },
            },
        },
    },
    walletTx: {
        tx_deposit_salary: {
            id: "tx_deposit_salary",
            walletId: "wallet_bank",
            type: "deposit",
            date: "2025-04-01",
            amount: { value: 3400, currency: "EUR" },
            createdAt: "2025-04-01T08:40:00.000Z",
        },
        tx_withdraw_rent: {
            id: "tx_withdraw_rent",
            walletId: "wallet_bank",
            type: "withdraw",
            date: "2025-04-02",
            amount: { value: 1200, currency: "EUR" },
            createdAt: "2025-04-02T09:20:00.000Z",
        },
        tx_forex_travel: {
            id: "tx_forex_travel",
            walletId: "wallet_bank",
            type: "forex",
            date: "2025-04-04",
            from: { value: 300, currency: "EUR" },
            to: { value: 330, currency: "USD" },
            fees: { value: 2.5, currency: "EUR" },
            fxRate: 1.1,
            createdAt: "2025-04-04T11:30:00.000Z",
        },
        tx_buy_vuaa: {
            id: "tx_buy_vuaa",
            walletId: "wallet_broker",
            type: "buy",
            date: "2025-03-10",
            assetId: "asset_vuaa",
            quantity: 18.5,
            price: { value: 91.2, currency: "EUR" },
            fees: { value: 1.5, currency: "EUR" },
            createdAt: "2025-03-10T10:05:00.000Z",
        },
        tx_buy_btc: {
            id: "tx_buy_btc",
            walletId: "wallet_broker",
            type: "buy",
            date: "2025-03-15",
            assetId: "asset_btc",
            quantity: 0.028,
            price: { value: 41200, currency: "USD" },
            fxPair: "EUR/USD",
            fxRate: 1.09,
            fees: { value: 3.0, currency: "EUR" },
            createdAt: "2025-03-15T14:25:00.000Z",
        },
        tx_dividend_vuaa: {
            id: "tx_dividend_vuaa",
            walletId: "wallet_broker",
            type: "dividend",
            date: "2025-04-08",
            amount: { value: 14.2, currency: "EUR" },
            assetId: "asset_vuaa",
            createdAt: "2025-04-08T10:10:00.000Z",
        },
    },
    pies: {
        pie_core: {
            id: "pie_core",
            name: "Core Portfolio",
            assetIds: ["asset_vuaa", "asset_btc"],
            description: "Balanced ETF + crypto satellite",
            risk: 6,
        },
    },
    livePrices: {
        price_vuaa: {
            key: "price_vuaa",
            type: "stock",
            ticker: "VUAA",
            value: 96.45,
            updatedAt: "2025-04-10T14:25:00.000Z",
            source: "Stooq",
        },
        price_btc: {
            key: "price_btc",
            type: "crypto",
            ticker: "BTC",
            value: 45210,
            updatedAt: "2025-04-10T14:25:00.000Z",
            source: "CoinGecko",
        },
    },
    notifications: [],
};
